# Default values for mcp-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Controller configuration
controller:
  # MCPRegistry controller configuration
  mcpRegistry:
    # Enable MCPRegistry controller (conditional registration based on CRD existence)
    enabled: true

# Registry configuration
registry:
  # Enable registry creation
  enabled: true
  
  # Registry name
  name: "default-registry"
  
  # Registry source configuration
  source:
    # Source type (github, http, etc.)
    type: "github"
    
    # GitHub repository (only used when type is "github")
    repo: "docker/mcp-registry"
    
    # GitHub branch (optional, defaults to default branch)
    branch: "main"
    
    # Path within the repository (optional)
    path: "servers"
  
  # Refresh interval for registry updates
  refreshInterval: "5m"
  
  # Authentication configuration
  auth:
    # Secret name containing authentication credentials
    secretName: ""

# Operator configuration
operator:
  # Image configuration
  image:
    repository: ghcr.io/fantasynitrogen/mcp_operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # For security compliance (CKV_K8S_14), always specify a fixed tag
    tag: "latest"
    # Image digest (takes precedence over tag if specified)
    # For best security practices (CKV_K8S_43), use digest instead of tag
    # Example: sha256:abcd1234567890abcd1234567890abcd1234567890abcd1234567890abcd1234
    digest: ""

  # Image pull secrets
  imagePullSecrets: []

  # Service account configuration
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
    # Automatically mount service account token
    automountServiceAccountToken: true

  # Pod annotations
  podAnnotations: {}

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    seccompProfile:
      type: RuntimeDefault

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001
    capabilities:
      drop:
      - ALL

  # Resource requirements
  # Recommended configurations based on cluster size:
  #
  # Small clusters (1-50 MCPServers):
  #   requests: cpu: 50m, memory: 64Mi
  #   limits: cpu: 200m, memory: 256Mi
  #   optimization: maxConcurrentReconcilesMCPServer: 3, maxConcurrentReconcilesMCPRegistry: 2, gogcPercent: 80
  #
  # Medium clusters (51-200 MCPServers):
  #   requests: cpu: 100m, memory: 128Mi
  #   limits: cpu: 500m, memory: 512Mi
  #   optimization: maxConcurrentReconcilesMCPServer: 5, maxConcurrentReconcilesMCPRegistry: 3, gogcPercent: 100
  #
  # Large clusters (201+ MCPServers):
  #   requests: cpu: 200m, memory: 256Mi
  #   limits: cpu: 1000m, memory: 1Gi
  #   optimization: maxConcurrentReconcilesMCPServer: 8, maxConcurrentReconcilesMCPRegistry: 5, gogcPercent: 100
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Replica count
  replicaCount: 1

  # Liveness probe configuration
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20

  # Readiness probe configuration
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10

  # Resource optimization configuration
  optimization:
    # Maximum concurrent reconciles for MCPServer controller
    # Higher values increase throughput but consume more CPU/memory
    # Recommended: 3-10 depending on cluster size and available resources
    maxConcurrentReconcilesMCPServer: 5
    
    # Maximum concurrent reconciles for MCPRegistry controller
    # Lower values recommended as registry operations are less frequent
    # Recommended: 1-5 depending on number of registries
    maxConcurrentReconcilesMCPRegistry: 3
    
    # GOGC percentage for Go garbage collector
    # Lower values = more frequent GC = lower memory usage but higher CPU
    # Higher values = less frequent GC = higher memory usage but lower CPU
    # Default: 100, Recommended for constrained environments: 50-80
    gogcPercent: 100

# Metrics configuration
metrics:
  # Enable metrics
  enabled: true
  
  # Service configuration for metrics
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

  # ServiceMonitor for Prometheus Operator
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}
    annotations: {}
    interval: 30s
    scrapeTimeout: 10s

# Webhook configuration
webhook:
  # Enable admission webhooks
  enabled: true
  
  # Auto-detect cert-manager and disable webhooks if not found
  autoDetectCertManager: true

  # Webhook service configuration
  service:
    type: ClusterIP
    port: 9443

  # Certificate configuration
  certManager:
    enabled: true
    issuerRef:
      name: selfsigned-issuer
      kind: Issuer

  # CA bundle for webhook certificates (required when certManager is disabled)
  caBundle: ""

  # Webhook failure policy
  failurePolicy: "Fail"

  # Admission review versions
  admissionReviewVersions: ["v1", "v1beta1"]

  # Side effects
  sideEffects: "None"

  # Timeout in seconds
  timeoutSeconds: 10

# Backup configuration
backup:
  # Enable backup functionality
  # When disabled, secrets access permissions are not granted for security compliance
  enabled: false

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  
  # Additional rules for the operator
  rules: []

# Custom Resource Definitions
crds:
  # Install CRDs
  install: true
  
  # Keep CRDs on uninstall
  keep: false

# Namespace configuration
# For security compliance (CKV_K8S_21), avoid using default namespace
# Specify a dedicated namespace for the operator
namespaceOverride: "mcp"

# Common labels
commonLabels: {}

# Common annotations
commonAnnotations: {}

# Priority class name
priorityClassName: ""

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Network policy
networkPolicy:
  enabled: true
  ingress: []
  egress: []

# Extra environment variables
extraEnvVars: []

# Extra volumes
extraVolumes: []

# Extra volume mounts
extraVolumeMounts: []

# Init containers
initContainers: []

# Sidecar containers
sidecars: []