# Default values for mcp-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Operator configuration
operator:
  # Image configuration
  image:
    repository: ghcr.io/fantasynitrogen/mcp_operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # For security compliance (CKV_K8S_14), always specify a fixed tag
    tag: "latest"
    # Image digest (takes precedence over tag if specified)
    # For best security practices (CKV_K8S_43), use digest instead of tag
    # Example: sha256:abcd1234567890abcd1234567890abcd1234567890abcd1234567890abcd1234
    digest: ""

  # Image pull secrets
  imagePullSecrets: []

  # Service account configuration
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
    # Automatically mount service account token
    automountServiceAccountToken: false

  # Pod annotations
  podAnnotations: {}

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    seccompProfile:
      type: RuntimeDefault

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001
    capabilities:
      drop:
      - ALL

  # Resource requirements
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Replica count
  replicaCount: 1

  # Liveness probe configuration
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20

  # Readiness probe configuration
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10

# Metrics configuration
metrics:
  # Enable metrics
  enabled: true
  
  # Service configuration for metrics
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

  # ServiceMonitor for Prometheus Operator
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}
    annotations: {}
    interval: 30s
    scrapeTimeout: 10s

# Webhook configuration
webhook:
  # Enable admission webhooks
  enabled: true
  
  # Webhook service configuration
  service:
    type: ClusterIP
    port: 9443

  # Certificate configuration
  certManager:
    enabled: false
    issuerRef:
      name: selfsigned-issuer
      kind: ClusterIssuer

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  
  # Additional rules for the operator
  rules: []

# Custom Resource Definitions
crds:
  # Install CRDs
  install: true
  
  # Keep CRDs on uninstall
  keep: false

# Namespace configuration
# For security compliance (CKV_K8S_21), avoid using default namespace
# Specify a dedicated namespace for the operator
namespaceOverride: "mcp"

# Common labels
commonLabels: {}

# Common annotations
commonAnnotations: {}

# Priority class name
priorityClassName: ""

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Network policy
networkPolicy:
  enabled: true
  ingress: []
  egress: []

# Extra environment variables
extraEnvVars: []

# Extra volumes
extraVolumes: []

# Extra volume mounts
extraVolumeMounts: []

# Init containers
initContainers: []

# Sidecar containers
sidecars: []