name: helm-publish-oci
description: Package charts in helm/* and push to GHCR OCI
inputs:
  helm-version:
    required: true
  token:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      with:
        version: ${{ inputs.helm-version }}
    - shell: bash
      run: echo "${{ inputs.token }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin
    - shell: bash
      run: |
        set -e
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        mkdir -p packaged
        if [ -d helm ]; then
          for chart in helm/*/; do
            [ -f "${chart}/Chart.yaml" ] || continue
            helm dependency update "${chart}" || true
            helm package "${chart}" -d packaged
          done
          for pkg in packaged/*.tgz; do
            [ -f "$pkg" ] || continue
            helm push "$pkg" "oci://ghcr.io/${REPO_OWNER}/helm-charts"
          done
        else
          echo "No helm/ dir"
        fi
