name: trivy-image-scan
description: Trivy scan by digest; uploads SARIF
inputs:
  image-ref: { required: true } # full ref image@sha256:...
runs:
  using: composite
  steps:
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        image-ref: ${{ inputs.image-ref }}
        format: sarif
        output: trivy-image.sarif
    - if: always() && hashFiles('trivy-image.sarif') != ''
      uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4
      with:
        sarif_file: trivy-image.sarif
        category: trivy-docker
      continue-on-error: true
