name: trivy-image-scan
description: Trivy scan by digest; uploads SARIF
inputs:
  image-ref: { required: true } # full ref image@sha256:...
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: ${{ inputs.image-ref }}
        format: sarif
        output: trivy-image.sarif
    - if: always() && hashFiles('trivy-image.sarif') != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-image.sarif
        category: trivy-docker
      continue-on-error: true
