name: trivy-image-scan
description: Trivy scan by digest; uploads SARIF
inputs:
  image-ref: { required: true } # full ref image@sha256:...
runs:
  using: composite
  steps:
    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
      with:
        image-ref: ${{ inputs.image-ref }}
        format: sarif
        output: trivy-image.sarif
    - if: always() && hashFiles('trivy-image.sarif') != ''
      uses: github/codeql-action/upload-sarif@df559355d593797519d70b90fc8edd5db049e7a2 # v3
      with:
        sarif_file: trivy-image.sarif
        category: trivy-docker
      continue-on-error: true
