apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mcp.allbeone.io/v1",
          "kind": "MCPServer",
          "metadata": {
            "name": "example-mcpserver"
          },
          "spec": {
            "registry": {
              "name": "filesystem-server"
            },
            "runtime": {
              "type": "python"
            },
            "replicas": 1
          }
        }
      ]
    capabilities: Deep Insights
    categories: Developer Tools,Integration & Delivery
    containerImage: ghcr.io/fantasynitrogen/mcp-operator:latest
    description: Kubernetes operator for managing MCP (Model Context Protocol) servers
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: mcp-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MCPServer is the Schema for the mcpservers API
      displayName: MCP Server
      kind: MCPServer
      name: mcpservers.mcp.allbeone.io
      version: v1
    - description: MCPServerBackup is the Schema for the mcpserverbackups API
      displayName: MCP Server Backup
      kind: MCPServerBackup
      name: mcpserverbackups.mcp.allbeone.io
      version: v1
  description: |
    ## About this Operator
    
    The MCP Operator manages MCP (Model Context Protocol) servers in Kubernetes clusters.
    It provides automated deployment, scaling, and lifecycle management of MCP servers
    with integration to the public MCP registry.
    
    ## Features
    
    * **Registry Integration**: Automatic deployment from MCP registry
    * **CLI Support**: Command-line tools for easy management
    * **Auto-scaling**: HPA and VPA support
    * **Backup & Restore**: Built-in backup functionality
    * **Multi-tenancy**: Namespace isolation and resource quotas
    * **Security**: Pod Security Standards and Network Policies
    
  displayName: MCP Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - mcp.allbeone.io
          resources:
          - mcpserverbackups
          - mcpservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mcp.allbeone.io
          resources:
          - mcpserverbackups/finalizers
          - mcpservers/finalizers
          verbs:
          - update
        - apiGroups:
          - mcp.allbeone.io
          resources:
          - mcpserverbackups/status
          - mcpservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: mcp-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: mcp-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: mcp-operator
          control-plane: controller-manager
        name: mcp-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: ghcr.io/fantasynitrogen/mcp-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mcp-operator-controller-manager
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mcp
  - model-context-protocol
  - ai
  - llm
  - kubernetes
  - operator
  links:
  - name: MCP Operator
    url: https://github.com/FantasyNitroGEN/mcp_operator
  maintainers:
  - email: support@example.com
    name: MCP Operator Team
  maturity: stable
  provider:
    name: FantasyNitroGEN
  version: 1.0.0