name: helm-lint-ct
description: Helm lint + chart-testing lint/install
inputs:
  helm-version:
    required: true
  chart-path:
    default: helm/mcp-operator
  ct-target-branch:
    default: main
  run-install:
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      with:
        version: ${{ inputs.helm-version }}
    - shell: bash
      run: |
        if [ -d "${{ inputs.chart-path }}" ]; then
          helm dependency update "${{ inputs.chart-path }}" || true
          helm lint "${{ inputs.chart-path }}"
        else
          echo "Chart not found at ${{ inputs.chart-path }} — skipping helm lint."
        fi
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.x'
    - uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
    - shell: bash
      run: |
        if [ -d "helm" ]; then
          ct lint --target-branch "${{ inputs.ct-target-branch }}" || true
        fi
    - if: ${{ inputs.run-install == 'true' }}
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        wait: 300s
    - if: ${{ inputs.run-install == 'true' }}
      shell: bash
      run: ct install --target-branch "${{ inputs.ct-target-branch }}"
