---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mcp-io-v1-mcpserver
  failurePolicy: Fail
  name: mmcpserver.kb.io
  rules:
  - apiGroups:
    - mcp.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mcpservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mcp-io-v1-mcpserver
  failurePolicy: Fail
  name: vmcpserver.kb.io
  rules:
  - apiGroups:
    - mcp.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mcpservers
  sideEffects: None
