name: helm-publish-pages
description: Package charts and publish to GitHub Pages
inputs:
  helm-version: { required: true }
runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      with:
        version: ${{ inputs.helm-version }}
    - shell: bash
      run: |
        set -e
        rm -rf gh-pages-charts
        mkdir -p gh-pages-charts
        if [ -d helm ]; then
          for chart in helm/*/; do
            [ -f "${chart}/Chart.yaml" ] || continue
            helm dependency update "${chart}" || true
            helm package "${chart}" -d gh-pages-charts
          done
        fi
        OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO="${{ github.event.repository.name }}"
        cd gh-pages-charts
        helm repo index . --url "https://${OWNER_LOWER}.github.io/${REPO}/"
    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
      with:
        path: gh-pages-charts
    - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
