name: helm-publish-pages
description: Package charts and publish to GitHub Pages
inputs:
  helm-version: { required: true }
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      with: { version: ${{ inputs.helm-version }} }
    - shell: bash
      run: |
        set -e
        rm -rf gh-pages-charts
        mkdir -p gh-pages-charts
        if [ -d helm ]; then
          for chart in helm/*/; do
            [ -f "${chart}/Chart.yaml" ] || continue
            helm dependency update "${chart}" || true
            helm package "${chart}" -d gh-pages-charts
          done
        fi
        OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO="${{ github.event.repository.name }}"
        cd gh-pages-charts
        helm repo index . --url "https://${OWNER_LOWER}.github.io/${REPO}/"
    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: gh-pages-charts
    - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
