name: setup-go-ci
description: Checkout + Setup Go + optional vet/test
inputs:
  go-version:
    required: true
  run-tests:
    default: "true"
  run-vet:
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
    - if: ${{ inputs.run-vet == 'true' }}
      shell: bash
      run: |
        go mod tidy
        go mod download
        go mod verify
        go vet ./...
    - if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: go test -race -cover ./...
