{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mcp-operator.networkPolicyName" . }}
  namespace: {{ include "mcp-operator.namespace" . }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mcp-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow metrics scraping
  {{- if .Values.metrics.enabled }}
  - from: []
    ports:
    - protocol: TCP
      port: 8080
  {{- end }}
  # Allow webhook traffic
  {{- if .Values.webhook.enabled }}
  - from: []
    ports:
    - protocol: TCP
      port: 9443
  {{- end }}
  # Allow health checks
  - from: []
    ports:
    - protocol: TCP
      port: 8081
  # Custom ingress rules
  {{- with .Values.networkPolicy.ingress }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow Kubernetes API access
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow webhook certificate management (cert-manager)
  {{- if .Values.webhook.certManager.enabled }}
  - to: []
    ports:
    - protocol: TCP
      port: 9402
  {{- end }}
  # Allow registry access for MCP server images
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Custom egress rules
  {{- with .Values.networkPolicy.egress }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}