{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-operator.metricsServiceName" . }}
  namespace: {{ include "mcp-operator.namespace" . }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "mcp-operator.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-operator.webhookServiceName" . }}
  namespace: {{ include "mcp-operator.namespace" . }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.service.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "mcp-operator.selectorLabels" . | nindent 4 }}
{{- end }}