name: kind-install-operator
description: Create kind cluster and install operator via Helm
inputs:
  chart-path: { default: helm/mcp-operator }
  namespace:  { default: mcp }
  helm-version: { required: true }
runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      with: { wait: 300s, cluster_name: mcp-e2e }
    - shell: bash
      run: kubectl create namespace "${{ inputs.namespace }}" || true
    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      with: { version: ${{ inputs.helm-version }} }
    - shell: bash
      run: |
        set -e
        if [ -d "${{ inputs.chart-path }}" ]; then
          helm upgrade --install mcp-operator "${{ inputs.chart-path }}" \
            --namespace "${{ inputs.namespace }}" --create-namespace
        else
          helm repo add mcp-operator https://fantasynitrogen.github.io/mcp_operator/
          helm repo update
          helm upgrade --install mcp-operator mcp-operator/mcp-operator \
            --namespace "${{ inputs.namespace }}" --create-namespace
        fi
        kubectl -n "${{ inputs.namespace }}" rollout status deploy/mcp-operator --timeout=600s
        echo "Operator image:"
        kubectl -n "${{ inputs.namespace }}" get deploy mcp-operator -o jsonpath='{.spec.template.spec.containers[0].image}'; echo
