name: e2e-kind

on:
  workflow_run:
    workflows: ["Release"]   # имя workflow из docker.yml (name:)
    branches: [ main, develop ]            # где он запускается
    types: [completed]

permissions:
  contents: read
  packages: read

jobs:
  e2e-postgres:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: mcp-e2e

      - name: Ensure namespace mcp exists
        run: kubectl create namespace mcp || true

      - name: Build operator image (no push)
        run: |
          DOCKER_BUILDKIT=1 docker buildx build \
            --load --platform linux/amd64 \
            -t mcp_operator:dev .

      - name: Load image into kind
        run: kind load docker-image mcp_operator:dev --name mcp-e2e

      - name: Install MCP Operator (Helm)
        run: |
          set -e

          # 1) ставим чарт как есть, в ns mcp
          if [ -d ./helm/mcp-operator ]; then
            helm upgrade --install mcp-operator ./helm/mcp-operator \
              --namespace mcp --create-namespace
          else
            helm repo add mcp-operator https://fantasynitrogen.github.io/mcp_operator/
            helm repo update
            helm upgrade --install mcp-operator mcp-operator/mcp-operator \
              --namespace mcp --create-namespace
          fi

          # 2) убеждаемся, какой образ реально прописан в деплойменте
          OP_IMG="$(kubectl -n mcp get deploy mcp-operator -o jsonpath='{.spec.template.spec.containers[0].image}')"
          echo "Operator image detected: $OP_IMG"

          # 3) если по какой-то причине это не latest из GHCR — мягко поправим на latest
          if ! echo "$OP_IMG" | grep -q "^ghcr.io/fantasynitrogen/mcp_operator:latest$"; then
            CTN="$(kubectl -n mcp get deploy mcp-operator -o jsonpath='{.spec.template.spec.containers[0].name}')"
            echo "Fixing image to ghcr.io/fantasynitrogen/mcp_operator:latest (container=$CTN)"
            kubectl -n mcp set image deploy/mcp-operator "${CTN}=ghcr.io/fantasynitrogen/mcp_operator:latest" --record
          fi

          # 4) ждём поднимание с увеличенным таймаутом; если что — собираем диагностику
          if ! kubectl -n mcp rollout status deploy/mcp-operator --timeout=600s; then
            echo "Rollout timed out — diagnostics:"
            kubectl -n mcp get pods -o wide || true
            kubectl -n mcp describe deploy mcp-operator || true
            kubectl -n mcp describe pods -l app.kubernetes.io/name=mcp-operator || true
            kubectl -n mcp get events --sort-by=.lastTimestamp | tail -n 200 || true
            kubectl -n mcp logs deploy/mcp-operator --all-containers --tail=200 || true
            exit 1
          fi

      - name: Build CLI
        run: go build -o ./bin/mcp ./cmd/mcp

      # --- Postgres in-cluster (битнами чарт) ---
      - name: Add Bitnami repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Install PostgreSQL
        run: |
          helm upgrade --install pg bitnami/postgresql \
            --namespace mcp \
            --set auth.postgresPassword=postgres \
            --set auth.database=app \
            --set primary.resources.requests.cpu=50m \
            --set primary.resources.requests.memory=128Mi
          kubectl -n mcp rollout status statefulset/pg-postgresql --timeout=300s

      - name: Compute POSTGRES_URL
        id: pgurl
        shell: bash
        run: |
          URL="postgresql://postgres:postgres@pg-postgresql.mcp.svc.cluster.local:5432/app?sslmode=disable"
          echo "URL=${URL}" >> $GITHUB_OUTPUT

      # --- Deploy MCP Postgres server from registry ---
      - name: Deploy MCP server (postgres) from registry
        run: |
          ./bin/mcp server deploy postgres \
            --namespace mcp \
            --replicas 1 \
            --env POSTGRES_URL='${{ steps.pgurl.outputs.URL }}' \
            --wait --timeout 300s

      - name: Validate status
        run: |
          kubectl -n mcp get mcpservers -o wide
          kubectl -n mcp get pods -l app.kubernetes.io/instance=postgres
          kubectl -n mcp wait mcpserver/postgres --for=condition=Ready --timeout=120s || true

      - name: Dump diagnostics on failure
        if: failure()
        run: |
          kubectl -n mcp get all
          kubectl -n mcp describe mcpserver postgres || true
          kubectl -n mcp logs deploy/mcp-operator || true
