---
name: Helm Chart

on:
  push:
    branches: [main, develop]
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yml'
  pull_request:
    branches: [main]
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yml'
  release:
    types: [published]

permissions:
  contents: read
  security-events: write

env:
  HELM_VERSION: v3.14.0

jobs:
  lint-and-test:
    name: Lint and Test Helm Charts
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-testing (list-changed)
        id: list
        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: steps.list.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0
        with:
          wait: 300s

      - name: Run chart-testing (install)
        if: steps.list.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

  security-scan:
    name: Security Scan Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run Checkov on Helm charts
        uses: bridgecrewio/checkov-action@master
        with:
          directory: helm/
          framework: helm
          output_format: sarif
          output_file_path: checkov-helm.sarif

      - name: Upload Checkov scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('checkov-helm.sarif') != ''
        with:
          sarif_file: checkov-helm.sarif
          category: checkov-helm
        continue-on-error: true

      - name: Run Trivy on Helm charts
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'helm/'
          format: 'sarif'
          output: 'trivy-helm.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('trivy-helm.sarif') != ''
        with:
          sarif_file: 'trivy-helm.sarif'
          category: trivy-helm
        continue-on-error: true

  package-and-publish:
    name: Package and Publish Helm Charts
    runs-on: self-hosted
    needs: [lint-and-test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm charts
        run: |
          mkdir -p ./packaged-charts
          for chart in helm/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename "$chart")
              echo "Packaging chart: $chart_name"
              helm dependency update "$chart"
              helm package "$chart" --destination ./packaged-charts/
            fi
          done

      - name: Push Helm charts to OCI registry
        run: |
          for package in packaged-charts/*.tgz; do
            if [ -f "$package" ]; then
              echo "Pushing $package to OCI registry"
              helm push "$package" oci://ghcr.io/${{ github.repository_owner }}/charts
            fi
          done

  release-charts:
    name: Release Helm Charts
    runs-on: self-hosted
    if: github.event_name == 'release'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Update chart versions
        run: |
          release_version="${{ github.event.release.tag_name }}"
          version="${release_version#v}"

          for chart in helm/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename "$chart")
              echo "Updating chart version for $chart_name to $version"
              sed -i "s/^version:.*/version: $version/" "$chart/Chart.yaml"
              sed -i "s/^appVersion:.*/appVersion: $version/" "$chart/Chart.yaml"
            fi
          done

      - name: Package and release Helm charts
        run: |
          mkdir -p ./release-charts
          for chart in helm/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename "$chart")
              echo "Packaging and releasing chart: $chart_name"
              helm dependency update "$chart"
              helm package "$chart" --destination ./release-charts/

              # Push to OCI registry with release tag
              for package in release-charts/${chart_name}-*.tgz; do
                if [ -f "$package" ]; then
                  helm push "$package" oci://ghcr.io/${{ github.repository_owner }}/charts
                fi
              done
            fi
          done

      - name: Upload chart packages to release
        uses: softprops/action-gh-release@v2
        with:
          files: release-charts/*.tgz