---
name: Helm Chart

on:
  workflow_run:
    workflows: [ "Release" ]
    branches: [ main, develop ]
    types: [ completed ]
  push:
    branches: [main, develop]
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yml'
  pull_request:
    branches: [main]
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yml'
  release:
    types: [published]

permissions:
  contents: read
  security-events: write

env:
  HELM_VERSION: v3.14.0

jobs:
  helm-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-lint-ct
        with:
          helm-version: v3.14.4
          chart-path: helm/mcp-operator
          ct-target-branch: main
          run-install: "true"

  publish-oci:
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-publish-oci
        with: { helm-version: v3.14.4 }

  publish-pages:
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-publish-pages
        with: { helm-version: v3.14.4 }
