---
name: Helm Chart

on:
  workflow_run:
    workflows: [ "Docker" ]
    branches: [ main, develop ]
    types: [ completed ]

concurrency:
  group: helm-${{ github.event.workflow_run.head_sha || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write
  pages: write
  id-token: write

env:
  HELM_VERSION: v3.14.0

jobs:
  helm-validate:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0
      - name: Debug refs
        run: |
          echo "event:        $GITHUB_EVENT_NAME"
          echo "job sha:      $GITHUB_SHA"
          echo "trigger sha:  ${{ github.event.workflow_run.head_sha }}"
          echo "trigger br:   ${{ github.event.workflow_run.head_branch }}"

      - name: Setup Go (for controller-gen)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Sync CRDs into Helm chart
        run: make sync-crds

      - name: Verify CRDs are in sync
        run: make check-crds

      - uses: ./.github/actions/helm-lint-ct
        with:
          helm-version: v3.14.4
          chart-path: helm/mcp-operator
          # важно: укажем базовую ветку, от которой считаем изменения чарта
          # если хочешь всегда сравнивать с main — оставь main
          # если нужно сравнивать с веткой триггера — подставляем head_branch:
          ct-target-branch: ${{ github.event.workflow_run.head_branch || 'main' }}
          run-install: "true"

  publish-oci:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0
      - name: Debug refs
        run: |
          echo "event:        $GITHUB_EVENT_NAME"
          echo "job sha:      $GITHUB_SHA"
          echo "trigger sha:  ${{ github.event.workflow_run.head_sha }}"
          echo "trigger br:   ${{ github.event.workflow_run.head_branch }}"

      - name: Setup Go (for controller-gen)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Sync CRDs into Helm chart
        run: make sync-crds

      - name: Verify CRDs are in sync
        run: make check-crds

      - uses: ./.github/actions/helm-publish-oci
        with:
          helm-version: v3.14.4
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-pages:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0
      - name: Debug refs
        run: |
          echo "event:        $GITHUB_EVENT_NAME"
          echo "job sha:      $GITHUB_SHA"
          echo "trigger sha:  ${{ github.event.workflow_run.head_sha }}"
          echo "trigger br:   ${{ github.event.workflow_run.head_branch }}"

      - name: Setup Go (for controller-gen)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Sync CRDs into Helm chart
        run: make sync-crds

      - name: Verify CRDs are in sync
        run: make check-crds

      - uses: ./.github/actions/helm-publish-pages
        with: { helm-version: v3.14.4 }
