---
name: Helm Chart

on:
  workflow_run:
    workflows: [ "Release" ]
    branches: [ main, develop ]
    types: [ completed ]


permissions:
  contents: read
  security-events: write
  packages: write
  pages: write
  id-token: write

env:
  HELM_VERSION: v3.14.0

jobs:
  helm-validate:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-lint-ct
        with:
          helm-version: v3.14.4
          chart-path: helm/mcp-operator
          ct-target-branch: main
          run-install: "true"

  publish-oci:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-publish-oci
        with:
          helm-version: v3.14.4
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-pages:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    needs: helm-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/helm-publish-pages
        with: { helm-version: v3.14.4 }
